[package]
name = "artemis-daw"
version = "0.1.0"
authors = ["Amber-Studios"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "artemis-daw"
path = "src/main.rs"
